<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	
	<!-- Favicon !-->
	<link rel="icon" href="Resources/favicon.png" type="image/png">
	
	<title>LightUp GFM (GitHub flavored Markdown) Renderer</title>
	
	<!-- Bootstrap CSS - just 4 styling ;)  -->
	<link rel="stylesheet" href="Resources/bootstrap.min.css" />
	<link rel="stylesheet" href="Resources/bootstrap-theme.min.css" />
	<link rel="stylesheet" href="Resources/Template.css" />
	
	<!-- Syntax Highlighting provided by EnlighterJS -->
	<!-- Include EnlighterJS Styles -->
	<link rel="stylesheet" type="text/css" href="Resources/EnlighterJS.yui.css" />
	
	<!-- Include MooTools Framework -->
	<script type="text/javascript" src="Resources/mootools-core-1.4.5-full-nocompat.js"></script>

	<!-- Include EnlighterJS -->
	<script type="text/javascript" src="Resources/EnlighterJS.yui.js" ></script>
		
	<!-- Initialize EnlighterJS; set default language+theme as well as some options -->	
	<meta name="EnlighterJS" content="Advanced javascript based syntax highlighting" data-indent="4" data-selector-block="pre.EnlighterJS" data-selector-inline="code" />
	
</head>
<body>
	<!-- Topnav -->
	<div id="navbar-wrapper">
		<div class="container">
			<div class="navbar navbar-inverse" role="navigation">
				<div class="navbar-header">
					<a class="navbar-brand" href="Example.php">LightUp</a>
				</div>
				<ul class="nav navbar-nav">
					<li><a href="Example.php">Readme</a></li>
					<li><a href="Quickstart.php">Quickstart</a></li>
					<li><a href="Example.php?doc=GfmReference">Markdown Reference</a></li>
				</ul>
				<ul class="nav navbar-nav navbar-right">
					<li><a href="https://github.com/AndiDittrich/LightUp/archive/master.zip">Get LightUp<b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li class="dropdown-header">Get it from GitHub</li>
							<li><a href="https://github.com/AndiDittrich/LightUp/archive/master.zip">Download (latest)</a></li>
							<li><a href="https://github.com/AndiDittrich/LightUp">Browse on GitHub</a></li>
						</ul>
					</li>
				</ul>
			</div>
		</div>
	</div>
	<!-- // topnav -->


	<!-- Begin page content -->
	<div class="container">
		<?php
			if (preg_match('/.*\<h1.*$/UAm', $pageContent)!==1){		
		?>
		<div class="page-header">
			<h1>
				<strong>LightUp</strong> <small>GFM (GitHub flavored Markdown) Renderer</small>
			</h1>
		</div>
		<?php } ?>
		<div id="content">
			<!-- ############################################################# -->
			<?php echo $pageContent; ?>
			<!-- ############################################################# -->

		</div>
		<!-- // content -->


	</div>
	<!-- // container -->

	<!-- Sticky Footer Message -->
	<div id="footer">
		<div class="container">
			<p class="text-muted">
				<strong>LightUp</strong> is developed by <a href="http://andidittrich.de">Andi Dittrich</a><br /> <a href="https://github.com/AndiDittrich/LightUp/archive/master.zip">Download</a> LightUp on <a href="https://github.com/AndiDittrich/LightUp">GitHub</a> | It's released under the Terms of <a href="LICENSE.md">MIT X11 License</a> | Demo created with <a href="http://getbootstrap.com">Bootstrap</a>
			</p>
		</div>
	</div>
	<!-- // Sticky Footer Message -->

</body>
</html>